# Generated by Django 3.0.5 on 2020-04-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vnrecc', '0002_auto_20200402_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
